spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':  # Ovo će primeniti CORS na sve rute
            allowedOrigins: "http://localhost:4200"  # Dozvoljava zahteve sa ovog origin-a
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: relational_service
          uri: http://localhost:8081  # URI relacione baze
          predicates:
            - Path=/api/relational/**
          filters:
            - StripPrefix=2
        - id: document_service
          uri: http://localhost:8082  # URI dokument baze
          predicates:
            - Path=/api/document/**
          filters:
            - StripPrefix=2
