spring:
  cloud:
    gateway:
      routes:
        - id: relational_service
          uri: http://localhost:8081  # URI relacione baze
          predicates:
            - Path=/api/relational/**
          filters:
            - StripPrefix=2
        - id: document_service
          uri: http://localhost:8082  # URI dokument baze
          predicates:
            - Path=/api/document/**
          filters:
            - StripPrefix=2
